name: internet_connection_listener
description: A simple package to show a No Internet Connection page using Flutter.
version: 0.0.5
homepage: https://github.com/zamizayn/internet_listener
repository: https://github.com/zamizayn/internet_listener

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  connectivity_plus: ^5.0.2


flutter:
  uses-material-design: true
  
